// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hQVQPOOOOQO'#C_'#C_QVQPOOOOQO-E6]-E6]",
  stateData: "[~OUOS~OQPO~O",
  goto: "ZSPPPTQQORRQ",
  nodeNames: "⚠ ClassNames ClassName",
  maxTerm: 6,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#a~R`X^!Tpq!T}!O!x!Q![!x![!]!x!c!}!x#R#S!x#T#o!x#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YYU~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!}UQ~}!O!x!Q![!x![!]!x!c!}!x#R#S!x#T#o!x",
  tokenizers: [0],
  topRules: {"ClassNames":[0,1]},
  tokenPrec: 0
})
